"""
Extract Required-section either/or choice groups from the SU degree pages.

Some programs let a student satisfy a requirement by taking one of several
interchangeable courses, stated only in a footnote on the degree page
(``degrees/<PROGRAM>_<TERM>.html``), e.g.:

    "Students are required to complete either MATH 212 or MATH 201."
    "It is enough to complete one of these courses: IR 391 or IR 394."
    "either MATH 212 or both (MATH 201 and MATH 202)"
    "Only one of the following course pairs will be counted: (VA 301 or VA 303), ..."

These footnotes are NOT captured in the scraped catalog/graph data, so the
requirements tracker would otherwise flag every listed course as individually
mandatory. This module parses the footnotes into choice groups and writes
``data/requirement_choice_groups.json``, consumed by
``scheduler.requirements.compute_remaining``.

Output forms (mirrors the schema the requirements tracker accepts):
  * symmetric one-of-many  -> {"choose": 1, "options": ["A", "B"]}
  * compound alternatives  -> {"satisfied_by_any_of": [["A"], ["B", "C"]]}

Run:
  python -m scraper.extract_choice_groups            # rebuild the config
  python -m scraper.extract_choice_groups --dry-run  # print, do not write
"""
from __future__ import annotations

import argparse
import json
import re
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEGREES_DIR = ROOT / "degrees"
GRAPHS_DIR = ROOT / "data" / "degree_graphs"
OUT_PATH = ROOT / "data" / "requirement_choice_groups.json"

_COMMENT = (
    "AUTO-GENERATED by scraper/extract_choice_groups.py from the footnotes on the "
    "SU degree pages (degrees/*.html). Do not edit by hand; re-run the extractor "
    "(or scraper.build_degree_graphs) to regenerate. Either/or groups within the "
    "Required section: a group is satisfied once one of its alternatives is "
    "completed, so the unused alternatives are not reported as still-needed. Forms: "
    "{\"choose\": 1, \"options\": [...]} for symmetric one-of-many, and "
    "{\"satisfied_by_any_of\": [[...], [...]]} for compound rules (complete ALL "
    "courses in ANY ONE inner list). Keyed by program; applies to every cohort."
)

# A course code: subject (2-5 letters) + 3 digits + optional trailing letter.
_CODE = r"[A-Z]{2,5}\s*\d{3}[A-Z]?"
_CODE_RE = re.compile(_CODE)

# Footnote sentences that announce a required choice. Used to scope extraction
# so unrelated "X or Y" prose elsewhere on the page is ignored.
_TRIGGER = re.compile(
    r"either|one of|only one|enough|sufficient|required to complete", re.I
)

# "either X or both (Y and Z)"  ->  satisfied by X alone, or by Y and Z together.
_COMPOUND = re.compile(
    r"either\s+(" + _CODE + r")\s+or\s+both\s*\(?\s*(" + _CODE + r")\s+and\s+(" + _CODE + r")",
    re.I,
)
# A run of interchangeable codes: "X or Y" (or "X or Y or Z").
_RUN = re.compile(r"(" + _CODE + r"(?:\s+or\s+" + _CODE + r")+)", re.I)


def _clean(code: str) -> str:
    """Normalize whitespace inside a code: 'MATH  201' -> 'MATH 201'."""
    return re.sub(r"\s+", " ", code).strip().upper()


def _strip_html(html: str) -> str:
    """Drop tags and collapse whitespace to plain text."""
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", html))


def _footnote_segments(text: str) -> list[str]:
    """Return text spans starting at a trigger keyword up to the next sentence end."""
    segs = []
    for m in _TRIGGER.finditer(text):
        end = text.find(". ", m.end())
        end = len(text) if end == -1 else end
        segs.append(text[m.start():end])
    return segs


def _groups_from_segment(seg: str) -> list[list[list[str]]]:
    """Parse one footnote segment into a list of groups (each a list of alternatives)."""
    groups: list[list[list[str]]] = []
    compound_spans: list[tuple[int, int]] = []

    for m in _COMPOUND.finditer(seg):
        single, pair_a, pair_b = (_clean(m.group(i)) for i in (1, 2, 3))
        groups.append([[single], [pair_a, pair_b]])
        compound_spans.append((m.start(), m.end()))

    for m in _RUN.finditer(seg):
        # Skip runs already consumed by a compound match.
        if any(s <= m.start() < e for s, e in compound_spans):
            continue
        codes: list[str] = []
        for c in (_clean(x) for x in _CODE_RE.findall(m.group(1))):
            if c not in codes:
                codes.append(c)
        if len(codes) >= 2:
            groups.append([[c] for c in codes])

    return groups


def groups_from_html(html: str) -> list[list[list[str]]]:
    """Extract all choice groups from one degree/minor HTML page.

    Returns a list of groups; each group is a list of alternatives, each
    alternative a list of course codes (see ``_load_choice_groups`` in
    ``scheduler.requirements`` for the satisfaction semantics). Shared by the
    degree extractor and the minor scraper so both parse footnotes identically.
    """
    text = _strip_html(html)
    groups: list[list[list[str]]] = []
    for seg in _footnote_segments(text):
        groups.extend(_groups_from_segment(seg))
    return groups


def emit_group(alts: list[list[str]]) -> dict:
    """Render a group (list of alternatives) in the most readable config form."""
    return _emit(alts)


def canonical(alts: list[list[str]]) -> frozenset:
    """Order-independent identity of a group, for de-duplication."""
    return _canonical(alts)


def _program_from_filename(name: str) -> str | None:
    """'BSCS-DM_202201.html' -> 'BSCS-DM'. Returns None if it has no built graph dir."""
    m = re.match(r"([A-Za-z0-9-]+)_\d{6}\.html$", name)
    if not m:
        return None
    program = m.group(1)
    return program if (GRAPHS_DIR / program).is_dir() else None


def _required_codes(program: str) -> set[str]:
    """Union of in-slice Required-section course codes across all cohorts of a program."""
    codes: set[str] = set()
    for jp in (GRAPHS_DIR / program).glob("*/Required.json"):
        data = json.loads(jp.read_text(encoding="utf-8"))
        codes |= {n["code"] for n in data.get("nodes", []) if n.get("in_slice")}
    return codes


def _canonical(alts: list[list[str]]) -> frozenset:
    """Order-independent identity of a group, for de-duplication across cohorts."""
    return frozenset(frozenset(a) for a in alts)


def _emit(alts: list[list[str]]) -> dict:
    """Render a group in the most readable accepted form."""
    if all(len(a) == 1 for a in alts):
        return {"choose": 1, "options": sorted(a[0] for a in alts)}
    norm = sorted((sorted(a) for a in alts), key=lambda a: (len(a), a))
    return {"satisfied_by_any_of": norm}


def build_choice_groups(write: bool = True, verbose: bool = True) -> dict:
    """Scan degree pages, extract validated choice groups, optionally write the config."""
    # program -> {canonical: alternatives}
    found: dict[str, "OrderedDict[frozenset, list[list[str]]]"] = {}
    for html_path in sorted(DEGREES_DIR.glob("*.html")):
        program = _program_from_filename(html_path.name)
        if program is None:
            continue
        html = html_path.read_text(encoding="utf-8", errors="ignore")
        for alts in groups_from_html(html):
            found.setdefault(program, OrderedDict())[_canonical(alts)] = alts

    out: "OrderedDict[str, list[dict]]" = OrderedDict()
    out["_comment"] = _COMMENT  # type: ignore[assignment]
    total = 0
    for program in sorted(found):
        required = _required_codes(program)
        groups = []
        for alts in found[program].values():
            # Keep only groups anchored to a real Required-section course. This
            # filters stray "X or Y" prose while still allowing an external
            # alternative (e.g. PROJ 300 as a substitute for required VA 300).
            all_codes = {c for a in alts for c in a}
            if not (all_codes & required):
                continue
            groups.append(_emit(alts))
        if groups:
            groups.sort(key=lambda g: json.dumps(g, sort_keys=True))
            out[program] = groups
            total += len(groups)

    if verbose:
        print(f"[choice-groups] {total} group(s) across "
              f"{len(out) - 1} program(s):")
        for program in out:
            if program == "_comment":
                continue
            print(f"  {program}: {out[program]}")

    if write:
        OUT_PATH.write_text(
            json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        if verbose:
            print(f"[choice-groups] wrote {OUT_PATH}")

    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true",
                    help="print the extracted groups but do not write the file")
    args = ap.parse_args()
    build_choice_groups(write=not args.dry_run)


if __name__ == "__main__":
    main()
